/**
 * Tests that the near-real fixture (generated by scripts/gen-near-real-fixture.ts)
 * is still adapter-compatible. If Anotator8 changes its schema and the
 * generator's hard-coded shape drifts, the adapter will reject it.
 *
 * This test runs after `npm run gen:fixture` is invoked. In CI we run
 * `npm run gen:fixture:check` which (a) writes the fixture and (b) exits
 * non-zero if the result is malformed.
 */
import { existsSync, readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { adapter } from "../../src/server/anotator8-adapter.js";

const FIXTURE_PATH = "fixtures/near-real-project.anotator8.json";

describe("near-real fixture (deterministic, gen:fixture)", () => {
  it("exists when the generator has been run", () => {
    // The fixture is gitignored; it must be generated before this test.
    // If missing, skip rather than fail (CI runs gen:fixture:check first).
    if (!existsSync(FIXTURE_PATH)) {
      // eslint-disable-next-line no-console
      console.warn(`[skip] ${FIXTURE_PATH} not present. Run: npm run gen:fixture`);
      return;
    }
    expect(existsSync(FIXTURE_PATH)).toBe(true);
  });

  it("adapter accepts it and produces >10 annotations across multiple shapes", () => {
    if (!existsSync(FIXTURE_PATH)) return;
    const raw = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as unknown;
    const project = adapter.normalize(raw);
    expect(project.annotations.length).toBeGreaterThan(10);
    const shapeTypes = new Set(project.annotations.map((a) => a.shapeType));
    expect(shapeTypes.size).toBeGreaterThanOrEqual(3);
  });

  it("preserves futureExtensionField as unknown", () => {
    if (!existsSync(FIXTURE_PATH)) return;
    const raw = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as Record<string, unknown>;
    const project = adapter.normalize(raw);
    expect(project.unknownFields.futureExtensionField).toBeDefined();
  });

  it("validator surfaces deterministic warnings (orphan cue + unknown annotation types)", () => {
    if (!existsSync(FIXTURE_PATH)) return;
    const raw = JSON.parse(readFileSync(FIXTURE_PATH, "utf8")) as unknown;
    const validation = adapter.validate(raw);
    const codes = validation.warnings.map((w) => w.code);
    expect(codes).toContain("ORPHANED_SUBTITLE_CUE");
  });
});
